#!/bin/sh -e

# desired behaviour
# shellcheck disable=SC2015
[ "$#" -eq 2 ] && [ -r "$1" ] || {
    printf "usage: %s file.tal.debug address\n" "$0" >&2
    exit 1
}

case "$1" in
    *.tal.debug) ;;
    *)
        printf "%s: does not end in .tal.debug, can't work out source file\n" "$1" >&2
        exit 1
    ;;
esac

debug_file="$1"
source_file="${1%.debug}"

compare_file_timestamps() {
    case "$(ls -t "$1" "$1.debug")" in
        "$1.debug"*) ;;
        *) printf "\033[1;33mWARNING\033[m: source file is newer than debug info\n" >&2 ;;
    esac
}

compare_file_timestamps "$source_file"

address="$(printf "%s" "$2" | tr 'a-f' 'A-F')"
dec_address="$(printf "16iAo%s 100-p\n" "$address" | dc || kill 0)"
# add 1 because the zeroth byte is on the first line
dec_address="$((dec_address + 1))"

is_integer() {
    printf %d "$1" >/dev/null 2>&1
}

token="$(sed -n "${dec_address}p" "$debug_file")"
: "${token:?cannot find integer from debug file at given byte}"
is_integer "$token" || {
    printf "can't find an integer token number in %s for byte %X\n" "$debug_file" "$address" >&2
    exit 1
}

print_highlighted() {
    index="$1"
    shift
    j=1
    for token; do
        if [ "$j" -eq "$index" ]; then
            printf " \033[1;31m%s\033[m" "$token"
        else
            printf " %s" "$token"
        fi
        j="$((j + 1))"
    done
    printf "\n"
}

i=0
lineno=0
while read -r line; do
    lineno="$((lineno + 1))"
    # word splitting is desired.
    # shellcheck disable=SC2086
    set -- $line
    i="$((i + $#))"
    [ "$i" -ge "$token" ] && {
        printf "line %d: " "$lineno"
        print_highlighted "$(($# - i + token))" "$@"
        break
    }
done < "$source_file"
